name: build

on:
  workflow_dispatch: {}
  # push:
  #  branches:
  #    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Install Yosys dependencies
        run: |
          sudo apt update
          sudo apt install -y bison build-essential clang flex gawk libboost-filesystem-dev libboost-python-dev libboost-system-dev libffi-dev libreadline-dev \
            git graphviz pkg-config python3 tcl-dev xdot zlib1g-dev
      - name: Build
        run: ./build.sh
      - name: Publish
        run: ./publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - name: Commit and tag
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          author_name: Daniel Huisman
          author_email: daniel@huisman.me
          message: 'Release v${{ env.NEW_VERSION }}'
          pull: 'NO-PULL'
          push: true
          tag: 'v${{ env.NEW_VERSION }}'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v${{ env.NEW_VERSION }}'
          name: 'Yosys.js v${{ env.NEW_VERSION }}'
          body: 'WebAssembly version of Yosys https://github.com/YosysHQ/yosys/commit/${{ env.UPSTREAM_COMMIT }}.'
